### ISSUE TITLE
Section from external Markdown file

### ISSUE THREAD

**Issue by mdbergmann** [melisgl/mgl-pax#10]
Hi.

It would be cool if I could specify a section `defsection` and just define a path `#P"somepath"` to where a Markdown file is.
This Markdown file is then just loaded and added as a section to the generated documentation.

Currently it is possible to write Markdown as part of a section's docstring. However, this usually happens in a Lisp highlighted environment (editor) and is harder to write. Otherwise I could use any writing environment and just 'include' the md file.

**Comment by mdbergmann** [comment]
I could come up with a macro like this that can render a Markdown file as section.

```lisp
(defmacro defsection-extmd (name path
                            (&key
                               title
                               (package '*package*)
                               (readtable '*readtable*)))
  (alexandria:with-gensyms (file-content entries)
    `(progn
       (let* ((,file-content (str:from-file ,path))
              (,entries (list ,file-content)))
         (pax::export-some-symbols ',name ,entries ,package)
         (defparameter ,name
           (make-instance 'pax:section
                          :name ',name
                          :package ,package
                          :readtable ,readtable
                          :title ,title
                          :entries (pax::transform-entries ,entries)))))))
```

But it has a few problems: 

1. it copies much of the original `defsection` macro. First I though I could just wrap the original macro in another macro and add the file-content as `entries`. But this seems to be beyond my CL skills.
2. Since it's defined outside of the `pax` package it has to use internal functions.
3. I'm not sure if there is a better way to do this. I.e. by defining a reference object that can load external content or so.

**Comment by melisgl** [comment]
The INCLUDE locative was intended to cover this use case:
https://melisgl.github.io/mgl-pax-world/mgl-pax-manual.html#x-28MGL-PAX-3AINCLUDE-20-28MGL-PAX-3ALOCATIVE-29-29

**Comment by mdbergmann** [comment]
OK, sorry for not properly reading the documentation.
Pretty cool.
