### ISSUE TITLE
Workflow for keeping documentation up-to-date?

### ISSUE THREAD

**Issue by lukego** [melisgl/mgl-pax#19]
@melisgl Thanks for your great work on MGL-PAX! I have been experimenting with it lately and really enjoying it. I'd like to start adopting it on projects "for real."

This leads me to wonder: How does one usually setup MGL-PAX documentation generation on an ongoing basis? How do you keep the READMEs up-to-date, update a HTML site, etc? I didn't see this covered in the docs or understand how it's done for your own projects.

There seems to be an opportunity to onboard the Kons-9 3D modeller into the PAX universe at the moment (https://github.com/kaveh808/kons-9/pull/219). That seems like a great fit. The native coding style there is quite spartan, without docstrings or symbol exports, and it's impressive that PAX can accommodate this as an add-on package that defines the PAX sections and installs the docstrings in the image.

Any points and tips would be appreciated :)

**Comment by melisgl** [comment]
I'm very happy to hear that you are enjoying PAX. In the linked Kons-9 commit, the injection of docstrings is a nice trick to get documentation generation working. As to the workflow, I'm afraid it's my time to admit to being quite spartan about it. Most of it is described in https://melisgl.github.io/mgl-pax-world/pax-manual.html#MGL-PAX:@GITHUB-WORKFLOW%20MGL-PAX:SECTION.

What's not spelled out there is that I manually call PAX:UPDATE-ASDF-SYSTEM-READMES and PAX:UPDATE-ASDF-SYSTEM-HTML-DOCS. An extra commit is to be made in the `doc/` (git worktree) directory.

Git has precommit hooks. Something like that could be used, but I haven't done it myself.

Also related to workflow, you may want to check out the new in-Emacs, live [documentation and apropos browser](https://melisgl.github.io/mgl-pax-world/pax-manual.html#MGL-PAX:@DOCUMENTING-IN-EMACS%20MGL-PAX:SECTION). Being able to quickly browse documentation (e.g. of a single function or a whole section) without an explicit documentation generation step tightens the documentation writing loop. Of course, you may want to go all in and write code and documentation together :-).

**Comment by lukego** [comment]
Github Actions to automatically build and publish HTML docs to Github Pages seems like a reasonable start: https://github.com/kaveh808/kons-9/blob/main/.github/workflows/generate-documentation.yml

I will check out the live documentation browser, thanks for the tip :)

**Comment by lukego** [comment]
> you may want to check out the new in-Emacs, live [documentation and apropos browser](https://melisgl.github.io/mgl-pax-world/pax-manual.html#MGL-PAX:@DOCUMENTING-IN-EMACS%20MGL-PAX:SECTION)

I love it! :grin:
