### ISSUE TITLE
Can't build today - missing symbol RESOLVE

### ISSUE THREAD

**Issue by quicklisp** [melisgl/mgl-pax#2]
Log is here:

http://report.quicklisp.org/2015-02-20/failure-report/mgl-pax.html#mgl-pax

    ; caught ERROR:
    ;   READ error during COMPILE-FILE: Symbol "RESOLVE" not found in the MGL-PAX package.Line: 395, Column: 64, File-Position: 14252Stream: #<SB-SYS:FD-STREAM for "file /home/quicklisp/quicklisp-controller/dist/build-cache/mgl-pax/f777bc675bcbbf9c8753198b4576f0bf53356dcd/mgl-pax-20150220-git/src/utility.lisp" {1011C33683}>
Unhandled UIOP/LISP-BUILD:COMPILE-FILE-ERROR in thread #<SB-THREAD:THREAD "main thread" RUNNING {1004407A53}>: COMPILE-FILE-ERROR while compiling #<CL-SOURCE-FILE "mgl-pax" "src" "utility">

**Comment by melisgl** [comment]
I'm told this was fixed by and update.
