### ISSUE TITLE
Missing `*DOCUMENT-URL-VERSIONS*` among others when loading `mgl-pax` system

### ISSUE THREAD

**Issue by paulapatience** [melisgl/mgl-pax#22]
Is the following intended?

```
$ rlwrap sbcl --noinform
* (require 'asdf)
("ASDF" "asdf" "UIOP" "uiop")
* (asdf:load-system "mgl-pax")
T
* (find-symbol "*DOCUMENT-URL-VERSIONS*" :mgl-pax)
NIL
NIL
* (asdf:load-system "mgl-pax/document")
WARNING:
   redefining EMACS-INSPECT (#<SB-PCL:SYSTEM-CLASS COMMON-LISP:T>) in DEFMETHOD
T
* (find-symbol "*DOCUMENT-URL-VERSIONS*" :mgl-pax)
MGL-PAX:*DOCUMENT-URL-VERSIONS*
:EXTERNAL
```

Some variables in `src/document/document.lisp` are present, some absent after loading just the `mgl-pax` system. I see that some functions are autoloaded, hence my asking if the behavior is intended, but from my admittedly brief look at the file, I couldn't figure out what could be causing the absent variables.

This behavior is present on `master` (303f48f3e0b8bfc75b1785d295ee56f2b9b0ec29), and also on commit ed82a80207b70801fab061f6592cf7d7355294a6.

**Comment by melisgl** [comment]
Thank you. Fixed in 80e99fe.
