### ISSUE TITLE
The symbol "METHOD" is not external in the MGL-PAX package

### ISSUE THREAD

**Issue by mdbergmann** [melisgl/mgl-pax#35]
Hello.

I've just updated MGL-PAX. 

It seems like the `PAX:METHOD` is not available anymore as for example used as part of a section:

```
  (ac:actor-of (pax:method () (asys:actor-system)))
```

PAX:READER, PAX:ACCESSOR, etc. are still available.

Am I looking wrong?

**Comment by melisgl** [comment]
Yes, this a consequence of factoring out the DREF library. PAX:METHOD is now DREF:METHOD; both EQ to CL:METHOD. I suggest using CL:METHOD. Is that satisfactory?

**Comment by melisgl** [comment]
Ah, I'll look into the PAX:READER thing tomorrow.

**Comment by mdbergmann** [comment]
> Yes, this a consequence of factoring out the DREF library. PAX:METHOD is now DREF:METHOD; both EQ to CL:METHOD. I suggest using CL:METHOD. Is that satisfactory?

Sure, that's totally fine. It works, thank you.
