### ISSUE TITLE
Package SWANK-BACKEND does not exist

### ISSUE THREAD

**Issue by Ambrevar** [melisgl/mgl-pax#6]
I'm trying to package mgl-pax for [Guix](https://www.gnu.org/software/guix) but it fails with

```
Package SWANK-BACKEND does not exist
```

I've posted an extensive report on [slime issue tracker](https://github.com/slime/slime/issues/457#event-1807320285).  @luismbo confirms that `swank-backend` has been renamed to `swank/backend` and that mgl-pax needs to reflect that.

I tried patching mgl-pax with a `s|swank-backend|swank/backend` substitution but it did not work.  Am I missing something?

**Comment by melisgl** [comment]
It was solved in the slime issue.
